[project]
name = "api-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aneezkunju", email = "aneezkunju@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic[email]>=2.13.4",
    "uvicorn>=0.52.3",
]

[project.scripts]
api-playground = "api_playground:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "httpx>=0.28.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3",
]
